Module Module1
    Public dicionario2 As String
    Public dicionario As Boolean
    Public formu1 As Boolean
    Public formu2 As Boolean
    Public formu3 As Boolean
    Public formu4 As Boolean
    Public formu5 As Boolean
    Public formu6 As Boolean
    Public formu7 As Boolean
    Public formu8 As Boolean
    Public formu9 As Boolean
    Public formu10 As Boolean
    Public formu11 As Boolean
    Public formu12 As Boolean
    Public formu13 As Boolean
    Public formu14 As Boolean
    Public formu15 As Boolean
    Public formu16 As Boolean
    Public formu17 As Boolean
    Public formu18 As Boolean
    Public formu19 As Boolean
    Public formu20 As Boolean
    Public formu21 As Boolean
    Public formu22 As Boolean
    Public formu23 As Boolean
    Public formu24 As Boolean
    Public formu25 As Boolean
    Public formu26 As Boolean
    Public formu27 As Boolean
    Public formu28 As Boolean
    Public formu29 As Boolean
    Public formu30 As Boolean
    Public formu31 As Boolean
    Public formu32 As Boolean
    Public formu33 As Boolean
    Public formu34 As Boolean
    Public formu35 As Boolean
    Public formu36 As Boolean
End Module
